# https://github.com/actions/starter-workflows/blob/main/deployments/azure-kubernetes-service-helm.yml

# https://docs.docker.com/guides/dotnet/configure-ci-cd/#step-two-set-up-the-workflow
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#using-environments-to-manually-trigger-workflow-jobs
# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-environments-for-deployment
# https://docs.github.com/en/actions/writing-workflows/quickstart
# https://docs.github.com/en/actions/writing-workflows/about-workflows
# https://docs.aws.amazon.com/prescriptive-guidance/latest/choosing-git-branch-approach/visual-overview-of-the-git-hub-flow-strategy.html

name: Build and deploy an app to AKS with Helm

on:
  push:
    branches: [$default-branch]
  workflow_dispatch:


jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          target: test
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          target: dev
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest


  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [buildImage]
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v4